
package com.stepsoln.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "NameService", targetNamespace = "http://server.ws.stepsoln.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface NameService {


    /**
     * 
     * @param lastName
     * @param firstName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getFullName(
        @WebParam(name = "firstName", partName = "firstName")
        String firstName,
        @WebParam(name = "lastName", partName = "lastName")
        String lastName);

}
