
package com.stepsoln.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NameServiceImplService", targetNamespace = "http://server.ws.stepsoln.com/", wsdlLocation = "http://localhost:8080/ws/nameService?wsdl")
public class NameServiceImplService
    extends Service
{

    private final static URL NAMESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.stepsoln.ws.server.NameServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.stepsoln.ws.server.NameServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ws/nameService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ws/nameService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NAMESERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public NameServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NameServiceImplService() {
        super(NAMESERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://server.ws.stepsoln.com/", "NameServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns NameService
     */
    @WebEndpoint(name = "NameServiceImplPort")
    public NameService getNameServiceImplPort() {
        return super.getPort(new QName("http://server.ws.stepsoln.com/", "NameServiceImplPort"), NameService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NameService
     */
    @WebEndpoint(name = "NameServiceImplPort")
    public NameService getNameServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.stepsoln.com/", "NameServiceImplPort"), NameService.class, features);
    }

}
